// Week_04/react-ws-intro/src/UserDetail.js
import React, { Component } from 'react';
import { Link } from "react-router-dom";
import './App.css';

class UserDetail extends Component {

  // Class properties 

  state = { user: {}, httpStatusCode: 0, httpStatusOk: false };

  url = `https://reqres.in/api/users/${this.props.id}`;

  componentDidMount() {

    // Get one
    fetch(this.url)
      .then(response => {
        // Optional...
        this.setState({ httpStatusCode: response.status, httpStatusOk: response.ok });
        if (response.ok) {
          // Parse the response body as JSON
          return response.json();
        } else if (response.status === 404) {
          // Not found 
          throw Error('HTTP 404, Not found');
        } else {
          // Some other situation
          throw Error(`HTTP ${response.status}, ${response.statusText}`);
        }
      })
      .then(responseData => {
        // "responseData" is an object; here, we're interested in its "data" property
        // Study the shape of the data in the reqres.in service
        this.setState({ user: responseData.data });
        // Optional...
        //console.log(responseData.data);
      })
      .catch(error => {
        // Handles an error thrown above, as well as network general errors
        console.log(error)
      });
  }

  render() {
    document.title = `User ${this.props.id} detail`;

    // For coding convenience, create a shortcut object
    const u = this.state.user;

    return (
      <div>
        <h4>Detail about user {u.first_name} {u.last_name} from the reqres.in service</h4>

        {/* <p>HTTP response status code was {this.state.httpStatusCode}</p> */}

        {this.state.httpStatusOk ? (
          <div className="row">
            <div className="col-md-6">
              <dl className="dl-horizontal">
                <dt>Identifier</dt><dd>{u.id}</dd>
                <dt>First name</dt><dd>{u.first_name}</dd>
                <dt>Last name</dt><dd>{u.last_name}</dd>
              </dl>
            </div>
            <div className="col-md-2">
              <img src={u.avatar} alt="" className="img-responsive" />
            </div>
          </div>

        ) : (
            <p>Requested user was not found</p>
          )}

        <hr />
        <p><Link className='btn btn-warning' to={`/users/edit/${u.id}`}>Edit</Link>&nbsp;&nbsp;
                    <Link className='btn btn-default' to='/users'>Show list of users</Link></p>
      </div>
    );
  }
}

export default UserDetail;

// Week_10/forms-validation-intro/src/app/user-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from "@angular/router";

import { DataModelManagerService } from "./data-model-manager.service";
import { ReqresUser } from "./data-model-classes";

@Component({
  selector: 'app-user-detail',
  templateUrl: './user-detail.component.html',
  styleUrls: ['./user-detail.component.css']
})
export class UserDetailComponent implements OnInit {

  // reqres.in web service data
  users: ReqresUser[];
  user: ReqresUser;

  constructor(private m: DataModelManagerService, private route: ActivatedRoute) { }

  ngOnInit() {

    // Get the route parameter
    let id = this.route.snapshot.params['id'];

    // Get one user, with identifier from above
    // The user is in the "data" property
    this.m.reqresUserGetById(id).subscribe(u => this.user = u.data);
  }

}

<h3>User detail</h3>
<p>&nbsp;</p>

<div class="row" *ngIf="user">
  <div class="col-md-6 col-sm-6">
    <dl class="dl-horizontal">
      <dt>Identifier</dt>
      <dd>{{ user.id }}</dd>
      <dt>First name</dt>
      <dd>{{ user.first_name }}</dd>
      <dt>Last name</dt>
      <dd>{{ user.last_name }}</dd>
    </dl>
  </div>
  <div class="col-md-2 col-sm-4">
    <img [src]="user.avatar" alt="" class="img-rounded img-responsive">
  </div>
</div>
<div *ngIf="user">
  <hr>
  <a routerLink="/users/edit/{{ user.id }}" class="btn btn-warning">Edit</a>&nbsp;
  <a routerLink="/users" class="btn btn-default">Back to list</a>
</div>

<div *ngIf="!user">
  <p>Requested user was not found</p>
  <p><a routerLink="/users" class="btn btn-default">Back to list</a></p>
</div>
